### ISSUE TITLE
I try to click the Search button on the the application (module 2, windows, start here, windows project) but it seems the api is returning 404

### ISSUE THREAD

**Issue by nunowallenstein** [fekberg/c-sharp-asynchronous-programming#1]
title
![imagem](https://user-images.githubusercontent.com/42320917/205405655-fd0a7a5d-0fe9-4b33-acfb-0a3d0e32a736.png)

**Comment by nunowallenstein** [comment]
Can you provide the api project on github so i can run it locally?

**Comment by fekberg** [comment]
Hi @nunowallenstein,

You will get 404 if you search for a stock that doesn't exist.

Try searching for MSFT with capital letters.

**Comment by nunowallenstein** [comment]
Thank you!
